# Site settings
title: Cornish Design Expo ’15
description: Cornish's Design BFA 2015 Expo, a public gallery of Cornish's senior design class in Seattle. View project previews and designer profiles here.
baseurl: ""
url: "http://cornishdesign.is"

# Build settings
markdown: kramdown
