# Site settings
title:        "Cornish Expo: Design 2015"
description:  >
              Cornish's Design BFA 2015 Expo, a public gallery 
              of Cornish's senior design class in Seattle. View 
              project previews and designer profiles here.
copyright:    >
              This website is an open source project on Github. 
              All projects and content are protected accordingly 
              by their respective owners.
# baseurl:      /
# url:          "http://cornishdesign.is"
url:          "http://rumudiez.github.io"
baseurl:      "/cornishdesign.is"

parent:       Cornish College of the Arts
parentURL:    "http://www.cornish.edu"
github:       "https://github.com/Rumudiez/cornishdesign.is"

# Build settings
markdown: kramdown
